### ISSUE TITLE
clickable taxon ranks

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#21]
Right now blue taxon nodes are clickable but green taxon rank nodes are not. Now that Deya is adding properties to the taxon rank concepts, we should make these green nodes clickable so we can display their properties.

**Comment by nhadlaw** [comment]
This is an easy fix, I would just need to know what to dispaly once a taxon rank is clicked. Right now I have it so that if a taxon rank is clicked nothing happens.

**Comment by touretzkyds** [comment]
@deyaliao  is adding some properties to the taxon ranks in the Devel graph. There should be "next higher" and "next lower" links, and of course rdfs:label. So treat this like a property display, except it's for a taxon rank instead of a taxon.

**Comment by deyaliao** [comment]
I believe the nextHigher and nextLower ranks should be displayed now on the graph, if you click on the taxonRank. Both Nelly and I worked on this.

**Comment by touretzkyds** [comment]
This is good, but it has a number of bugs. See image below. I'm not sure how to reproduce this.

![Coturnix](https://user-images.githubusercontent.com/1978092/176807253-5e284991-cb74-4f12-a99c-c5bf32d70da6.png)

To reproduce this next one, type "Coturnix" in the text box, click on the Genus node, then click on the Coturnix node to get the property view, then click on Genus again. We're graying out and then recreating the nextHigherRank and nextLowerRank arrows, but not recrerating the ranks themselves. Rather than do this we should just not gray the original arrows and nodes.
![Coturnix2](https://user-images.githubusercontent.com/1978092/176807821-1945a4ee-6f7b-4e11-bfef-5037e0bb74d6.png)

Also, the green taxon rank nodes should be changing appearance slightly on mouseover, like the blue taxon nodes do, to indicate that they are clickable.

Finally, at the bottom of the tree there are "temporary" nodes. I think this is part of Nelly's hack to fix the dagre formatting issue. Please get rid of this; it's not the right solution.

**Comment by deyaliao** [comment]
I do think this issue should be fixed now – I've indicated clickability for rank nodes and got rid of the background rank node.

**Comment by touretzkyds** [comment]
Yes, it's working correctly now.

**Comment by deyaliao** [comment]
I actually noticed another bug; if I use the navigation bar to navigate around the graph, the greyed out taxon ranks located at the concept's 270 degree angle doesn't properly close and open with regards to the navigation––making it still clickable in instances where I don't want it to be clickable. I will fix this tomorrow.

**Comment by deyaliao** [comment]
I've since fixed the original bug I was talking about, but I noticed that when you're currently displaying a taxon, the green ranks for the greyed out taxa nearby are still present and clickable. It looks a bit funny, so I do have three options to deal with these ranks: either hide all of them completely when we're in the middle of viewing a taxon, make them unclickable, or keep them clickable and transition to the taxon of the clicked rank (open up its new properties). See images below for reference. 

<img width="708" alt="Screen Shot 2022-07-06 at 1 48 41 PM" src="https://user-images.githubusercontent.com/61635230/177640389-a8ccb747-d5f8-46eb-a6e5-1010c0ff642c.png">
<img width="786" alt="Screen Shot 2022-07-06 at 1 48 45 PM" src="https://user-images.githubusercontent.com/61635230/177640411-cc5f5acf-35cf-4f15-8cf7-e0933fb63bc8.png">

**Comment by touretzkyds** [comment]
Let's go with the first of the three options and hide the nodes.

**Comment by deyaliao** [comment]
I believe it is fixed now.

**Comment by touretzkyds** [comment]
Looks good.
