### ISSUE TITLE
subtaxa should be ordered alphabetically

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#22]
Currently the child nodes of a taxon are laid out in what appears to be a random order. We should order them alphabetically based on their displayed names.

**Comment by nhadlaw** [comment]
From the few examples I looked through, it looks like the child nodes aren't laid out randomly, they're laid out in the order they appear in the Data.ttl file in the devel branch (outside of the dev folder) of the KnowledgeGraphServer git hub repository.  For example, "Prokaryota, boltz:Q19081" is defined as a taxon on line 423 of Data.ttl. We expect its children to be Bacteria and Animalia. These taxon's are defined on lines 432 and 744 respectively.  Another example is with "Tetrapoda, boltz: boltz:Q19159" which is a taxon defined on line 838 of Data.ttl and its children taxa are Aves, Reptiliomorpha, Mammaliaformes defined on lines 845, 960, and 1250 respectively. This makes sense because when the query is run to generate the hierarchy, it generates all child and parent relationships in the same order they are dispalyed in Data.ttl. I think it would probably be more efficient to change Data.ttl to have children defined alphabetically. I think this would be a more efficient solution so that with hundreds of children, when getting the json object from the query, we wouldn't have to worry about rearranging them to be alphabetical. I don't know how easy this can be but from my understanding if we do it once, we don't have to do it again, unlike if we were to always try and arrange children alphabetically when generating the cytoscape graph.

**Comment by touretzkyds** [comment]
This is an interesting suggestion, and I spent some time thinking about it, but in the end I think it's best not to make our code dependent on an assumption that can't be enforced: that items are kept in sorted order in the ttl file. Anyone who edits this file could accidentally put something in the wrong place and cause our code to return incorrect results. Also, we will want to enforce this alphabetical ordering in lots of other places, e.g., Microsoft owns dozens of companies, so when we present a list of its divisions, they should be alphabetical.

The safest thing is to do the sorting ourselves. For students who are writing their own Python code to query our knowledge graph, we're already going to be supplying them with template code for SPARQL queries. We can also throw in a utility function that sorts children alphabetically so they don't have to write it from scratch.

**Comment by nhadlaw** [comment]
The newest version of demo2.html should display children in alphabetical order. If I missed something or didn't see a bug in this implementation please let me know otherwise I think it'd be good to close this issue

**Comment by touretzkyds** [comment]
Looks good.
