### ISSUE TITLE
display of large text boxes

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#27]
Large text boxes like the description of "American alligator" are currently displaying as very tall and skinny rectangles. This doesn't look good.

We should use a wider width for large chunks of text, so that the box doesn't have to be so tall.

Also, we should not display these giant boxes by default. Instead let's display a regular sized box with the first few words of the text followed by ellipses ("..."), and include a little icon in the corner indicating that the box can be expanded to see the full text.

Clicking on the small box should expand it. Clicking on the expanded box should un-expand it.

**Comment by nhadlaw** [comment]
Do you want the definition boxes to be clickable for the hover feature as well? If so, what should the user have to do to make the definition go away? I ask this because right now the definition is only displayed when the user hovers over the taxon node that they want the description of. So either I can make the duration of the definition shown last longer, giving the user time to click it (to expand it) or just display the whole def in this instance.

**Comment by touretzkyds** [comment]
The pop-up definitions don't need to be clickable. They can display at full size, since it's easy for the user to get rid of them by moving the mouse a fraction of an inch. But it would be good if they were more square instead of super tall and skinny.

**Comment by nhadlaw** [comment]
Latest version of demo2.html should fix this issue

**Comment by touretzkyds** [comment]
This was closed too soon. The text box for Alligator mississippiensis has a nice shape now, but it also has weird line breaks, and the last sentence appears to be cut off. Also, when text exceeds one line we should switch to left-aligned format instead of centered.

![description](https://user-images.githubusercontent.com/1978092/172925293-7c29d902-fd48-40ce-a831-07ed92951f4b.png)

**Comment by nhadlaw** [comment]
Latest version of demo2.html fixes these issue. It turns out the larger text entries had line breaks so I just ended up replacing those with spaces. The sentence is not being cut off, I looked at Data.ttl and this is the definition entered into "Alligator mississipiensis" so I can go in and fix 'saltw' to 'salt' manually.

**Comment by touretzkyds** [comment]
If you remove all newlines you will lose the paragraph breaks. You should replace double newlines with some special marker like ##newline##, then change single newlines to spaces, then change ##newline## to a single newline.

Also, "saltw" should be "saltwater". The text comes from the Wikipedia article on "American alligator".

**Comment by touretzkyds** [comment]
I think I gave you bad advice. We should leave the newlines alone. Instead you should edit the ttl file to remove the spurious newlines in the text that Arthur pasted from Wikipedia. Also check the other entries to make sure we don't have the same problem with spurious newlines elsewhere.

**Comment by touretzkyds** [comment]
No further action needed at this time.
