### ISSUE TITLE
weird scaling in display update

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#35]
In the current version of demo2d, if I click on a blue taxon node and then climb up the tree by clicking on the blue nodes that are pointed to by subTaxonOf links, sometimes the display update messes up the scaling of the circles, forming ovals like this:

![bad_scale](https://user-images.githubusercontent.com/1978092/174493567-5636e813-1bd9-4a74-87b6-a164d2cd721d.png)

If I mouse over the pink circle then the shape updates and I get a proper circle.

Another issue is that the text in the pink circle is not correct. (It should be showing the taxon name and Q number). It looks like this text is what we should be seeing in the DEF pop-up box instead of the far less useful "Order of mammals".

**Comment by nhadlaw** [comment]
Sorry, I'm having trouble replicating this issue on my side. What is the series of steps that led you to the first issue. I.e. I tried typing in Primates to the text box and tried starting from one of its children to climb up to it and I'm not seeing the same issue.

**Comment by touretzkyds** [comment]
I can't reproduce it either. Weird.

But here's a problem I can reproduce: if I type "primates" in the search box, nothing happens. I don't get an error message the way I would if I typed in nonsense, but the display doesn't update either. Nothing happens at all. But if I type "primate" (without the "s") then I get the Primates node boltz:Q7380, as I should. Note that the node's prefLabel is "Primate" but the taxonName is "Primates".

**Comment by nhadlaw** [comment]
Ok I see what's happening. So when I type in "primates" the graph does actually adjust as it's supposed to but the change is so small it's hard to see when a user is zoomed out. If I type in "primates" and zoom in, I can see that now the red node is "Primates: Q7380" which has everything below it displayed and everything above it. If I type "Primate" the change is very noticeable because it's not correct.  There is a bug for the user typing in the prefLabel instead of the taxon name that sometimes produces the wrong graph. I am working on fixing this issue. So the correct thing that should happen is the "Primate" graph should look exactly the same as the "Primates" one which will still be a very large graph that's hard to see when a user is zoomed out.

**Comment by touretzkyds** [comment]
It looks like this issue has been resolved.
