### ISSUE TITLE
duplicate links in graphical display

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#4]
In the graphical display, Alligator has two subTaxonOf links to Alligatoridae, and Escherichia coli has two subTaxonOf links to Escherichia. Why is that?

**Comment by nhadlaw** [comment]
I was working on this issue yesterday. It occurred because when creating the property nodes for a specific taxon value, some of the properties displayed were "subtaxonOf" to the same parent node of the taxon value already present in the hierarchy. To fix this issue I just assigned unique id's to duplicated node elements, the current version of demo2.html on git hub should no longer have this issue.

**Comment by touretzkyds** [comment]
Are you saying we actually have redundant subTaxonOf links in the graph? Where did these duplicate links come from?

**Comment by nhadlaw** [comment]
When we run the property query on a taxon value some of the properties that come up are "subTaxonOf" some node.

**Comment by touretzkyds** [comment]
Then why doesn't every node have double links? Why is it only a few nodes?

**Comment by nhadlaw** [comment]
The important part of this reason is based on what display mode we're in. For example, consider the 'Concise' display mode. The reason the double links were being created was because if a user clicked a node like "Alligator", if the property produced by the query was "subTaxonOf" Alligatoridae (which has taxon rank 'Family' so it's going to be present in the Concise hierarchy) then a double link would be created. However for some nodes, like Chordata, it's a "subTaxonOf" Deuterostome which has taxon rank 'Superphylum' so the node 'Deuterostome' isn't present in the Concise hierarchy so there's no double link produced. I hope this clarifies the reasoning why only some nodes had double links. Once again, I believe this issue should be fixed.

**Comment by touretzkyds** [comment]
Verified as fixed.
