### ISSUE TITLE
pop-up descriptions are slow to appear and slow to disappear

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#6]
Pop-up descriptions are slow to show up. This appears to be because we're running a database query every time we need to fetch the description of a node. We should be fetching all these descriptions as part of the original query so we don't have to make new server requests every time the user drags their mouse over the graph.

Also, sometimes it takes quite a while for the pop-up box to go away. Since it can block other elements the user wants to look at, this is annoying. The behavior is not consistent, but it occurs fairly frequently. What is causing this?

**Comment by nhadlaw** [comment]
I will work on changing the pop up functionality however I noticed that having the pop-up box go away is indeed inconsistent with the simplest data. When I first was experimenting with the mouseover and mouseout cytoscape node functions I noticed that even just making a simple node (without any text) disappear with 'mouseout' was inconsistent. This means that it's speed doesn't have anything to do with the actual query being preformed I think it might be a problem with the way the node selection works (my thinking was maybe that the nodes are pretty close together so that may be an issue that's causing this). I can look into somehow making the disappearance faster but I wanted to point out that the speed of disappearance doesn't have to do with the actual content we are trying to display.

**Comment by nhadlaw** [comment]
Actually I think I may be wrong about the pop up disappearing, I am currently working on that issue right now and it seems like with simple nodes it works fine (faster than the old version of demo2) so I'm gonna see if changing the query will adjust this speed.
